import React, { useEffect, useState } from "react";
import NewsCard from "../NewsCard/NewsCard";
import { Box, Typography } from "@mui/material";
import axios from "axios";

function NewsContainer({ selectedSources }) {
  const [articles, setArticles] = useState([]);
  console.log("Selected sources:", selectedSources);

  useEffect(() => {
    // Map your sources to your scraping endpoints
    const sourceEndpoints = {
      "The Hollywood Reporter": "http://localhost:3001/scrape-hollywood",
      Deadline: "http://localhost:3001/scrape-deadline",
      Variety: "http://localhost:3001/scrape-variety",
      "New York Times": "http://localhost:3001/scrape-nyt",
      "Fox News": "http://localhost:3001/scrape-fox",
    };

    // Filter the sources to only those selected by the user
    const filteredSources = Object.entries(sourceEndpoints)
      .filter(([sourceName]) => selectedSources.includes(sourceName))
      .map(([, endpoint]) => endpoint);
    console.log("filteredSources:", filteredSources);

    if (filteredSources.length > 0) {
      Promise.all(filteredSources.map((url) => axios.get(url)))
        .then((responses) => {
          // You may need to adjust how you combine and set the articles based on the structure of your response
          const newArticles = responses.flatMap((response) => {
            const articleData = response.data;
            if (typeof articleData.summary === "string") {
              articleData.summary = JSON.parse(articleData.summary);
            }
            return articleData;
          });
          setArticles(newArticles);
        })
        .catch((error) => {
          console.error("Error fetching news:", error);
        });
    } else {
      // If no sources are selected, clear the articles
      setArticles([]);
    }
  }, [selectedSources]);

  if (articles.length === 0) {
    return <Typography>No article data available.</Typography>;
  }

  console.log("Articles:", articles);

  return (
    <Box
      sx={{
        display: "flex",
        flexDirection: "row",
        flexWrap: "wrap",
      }}
    >
      {articles.map((article, index) => (
        <NewsCard
          key={index}
          title={article.headline}
          summary={
            <React.Fragment>
              {" "}
              {/* Wrap the JSX with a React.Fragment */}
              <strong>Summary generated by OpenAI:</strong>{" "}
              {article.summary.summary}
            </React.Fragment>
          }
          source={article.source}
          sourceUrl={article.link}
          imageUrl={article.imageUrl}
        />
      ))}
    </Box>
  );
}

export default NewsContainer;
